export default {
    products: [
        {

            _id: '1',
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 12,
        },
        {
            _id: '2',
            name: 'Awesome Pants',
            category: 'Pants',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 0,
        },
        {
            _id: '3',
            name: 'Nice Pants',
            category: 'Pants',
            image: '/images/d1.jpeg',
            price: 100,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 10,
            countInStock: 3,
        },
        {
            _id: '4',
            name: 'Cheap Shirt',
            category: 'Shirts',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 1.5,
            numReviews: 100,
            countInStock: 22,
        },
        {
            _id: '5',
            name: 'Fancy Shirt',
            category: 'Shirts',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            countInStock: 1,
        },
    ],
};
