export default {
    products: [
        {
            name: 'Slim Shirt',
            category: 'Shirts',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            name: 'Awesome Pants',
            category: 'Pants',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
        {
            name: 'Nice Pants',
            category: 'Pants',
            image: '/images/d1.jpeg',
            price: 100,
            brand: 'Nike',
            rating: 2.5,
            numReviews: 10,
        },
        {
            name: 'Cheap Shirt',
            category: 'Shirts',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 1.5,
            numReviews: 100,
        },
        {
            name: 'Fancy Shirt',
            category: 'Shirts',
            image: '/images/d1.jpeg',
            price: 60,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
        },
    ],
};
